local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<leader>f', builtin.git_files, {})
vim.keymap.set('n', '<leader>b', ':Telescope buffers<cr>')
vim.keymap.set('n', '<leader>g', ':Telescope live_grep<cr>')
vim.keymap.set('n', '<leader>gf', function()
	builtin.grep_string({ search = vim.fn.input('Grep > ') })
end)
